---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

starknet:
  attestator:
    source_url: https://github.com/eqlabs/starknet-validator-attestation/releases/download
    ports:
      metrics_port: 9090
  node:
    source_url: https://github.com/eqlabs/pathfinder/releases/download
    ports:
      rpc_port: 9545
      metrics_port: 9685
