---
- name: Set up Starknet attestator
  hosts: all
  become: true
  gather_facts: true
  vars:
    allowed_node_types: [attestator]
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
    - group_vars/{{ env }}.yml

  pre_tasks:
    - name: Setup Pre Tasks
      when: type in allowed_node_types
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml

  tasks:
    - name: Run attestator role
      when: type in allowed_node_types
      block:
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include attestator role
          ansible.builtin.include_role:
            name: attestator
