---
- name: Include ufw vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ attestator_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ attestator_home_dir }}"
    directories: "{{ attestator_directories }}"
    log_file_path: "{{ attestator_log_file_path }}"

- name: Include extract binary task
  ansible.builtin.include_tasks: extract_binary.yml

- name: Fetch secrets environment file from HCP Vault and save to file
  ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
  vars:
    vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ attestator_environment_secret_file_name }}"
    secret_destination_path: "{{ attestator_environment_secret_file_path }}"
    secret_type: environment

- name: Copy general env file
  ansible.builtin.template:
    src: "{{ env }}/general.env.j2"
    dest: "{{ attestator_environment_general_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
